apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "0.0.0.0"
  #disableDefaultCNI: true
  apiServerPort: 6443
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8070 # eurekaserver
    hostPort: 8070
    #listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 80 # epoweredmove-web-front
    hostPort: 80
    #listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 8080 # gateway server
    hostPort: 8080
    #listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 9411 # zipkin
    hostPort: 9411
    #listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 5678 # test echo for metalLB
    hostPort: 5678
    #listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
#- role: worker
#networking:
#  kubeProxyMode: "none" #https://kind.sigs.k8s.io/docs/user/configuration/