# depl1LB.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  #replicas: 2
  replicas: 1
  selector:
    matchLabels:
      app: service-echo
  template:
    metadata:
      labels:
        lbtype: external
        app: service-echo
    spec:
      containers:
        - name: service1
          image: ghcr.io/moutansos/hellocontainers:latest
          resources:
            requests:
              cpu: "150m"
              memory: "100M"
            limits:
              cpu: "200m"
              memory: "200M"
          ports:
            - containerPort: 80
              name: "8081-port"              
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: HELLOCONTAINERS_MESSAGE
              value: 'Hello from Service 1!'
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        kubernetes.io/os: linux
---
