apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentmethod-deployment
  labels:
    app: paymentmethod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentmethod
  template:
    metadata:
      labels:
        app: paymentmethod
    spec:
      containers:
      - name: paymentmethod
        image: diamantopoulosconstantinos/paymentmethod:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: "300m"
            memory: "300M"
          limits:
            cpu: "400m"
            memory: "500M"
---
apiVersion: v1
kind: Service
metadata:
  name: paymentmethod-service
spec:
  selector:
    app: paymentmethod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
