apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-deployment
  labels:
    app: vehicle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle
  template:
    metadata:
      labels:
        app: vehicle
    spec:
      containers:
      - name: vehicle
        image: diamantopoulosconstantinos/vehicle:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: "300m"
            memory: "300M"
          limits:
            cpu: "400m"
            memory: "500M"
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
spec:
  selector:
    app: vehicle
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
