apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
  labels:
    app: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
      - name: gatewayserver
        image: diamantopoulosconstantinos/gatewayserver:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "150m"
            memory: "100M"
          limits:
            cpu: "200m"
            memory: "300M"
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver-service
spec:
  selector:
    app: gatewayserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
