apiVersion: apps/v1
kind: Deployment
metadata:
  name: poichargingstation-deployment
  labels:
    app: poichargingstation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poichargingstation
  template:
    metadata:
      labels:
        app: poichargingstation
    spec:
      containers:
      - name: poichargingstation
        image: diamantopoulosconstantinos/poichargingstation:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "150m"
            memory: "100M"
          limits:
            cpu: "200m"
            memory: "300M"
---
apiVersion: v1
kind: Service
metadata:
  name: poichargingstation-service
spec:
  selector:
    app: poichargingstation
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
