apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-backend-deployment
  labels:
    app: epoweredmove
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epoweredmove
  template:
    metadata:
      labels:
        app: epoweredmove
    spec:
      containers:
      - name: epoweredmove
        image: diamantopoulosconstantinos/epoweredmove:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: epoweredmove-service
spec:
  selector:
    app: epoweredmove
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
