apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewsreservations-deployment
  labels:
    app: reviewsreservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewsreservations
  template:
    metadata:
      labels:
        app: reviewsreservations
    spec:
      containers:
      - name: reviewsreservations
        image: diamantopoulosconstantinos/reviewsreservations:latest
        ports:
        - containerPort: 8004
        resources:
          requests:
            cpu: "50m"
            memory: "100m"
          limits:
            cpu: "50m"
            memory: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: reviewsreservations-service
spec:
  selector:
    app: reviewsreservations
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
