apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        lbtype: external
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "150m"
            memory: "100M"
          limits:
            cpu: "250m"
            memory: "300M"
        ports:
        - containerPort: 9411
          name: "9411-port"
