# depl2LB.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  #replicas: 2
  replicas: 1
  selector:
    matchLabels:
      app: service-echo
  template:
    metadata:
      labels:
        app: service-echo
    spec:
      containers:
        - name: service2
          image: ghcr.io/moutansos/hellocontainers:latest
          ports:
            - containerPort: 80
              name: http
              #name: testmetallb
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: HELLOCONTAINERS_MESSAGE
              value: 'Hello from Service 2!'
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        kubernetes.io/os: linux
---
